### ISSUE TITLE
Bug in new update? Windows OS. previous commit work OK

### ISSUE THREAD

**Issue by zelenooki87** [cswry/OSEDiff#40]
python test_osediff.py -i preset/datasets/test_dataset/input -o preset/datasets/test_dataset/output --osediff_path preset/models/osediff.pkl --pretrained_model_name_or_path preset/models/stable-diffusion-2-1-base --ram_ft_path preset/models/DAPE.pth --ram_path preset/models/ram_swin_large_14m.pth
Traceback (most recent call last):
  File "C:\Users\admin\OSEDiff\test_osediff.py", line 12, in <module>
    from osediff import OSEDiff_test
  File "C:\Users\admin\OSEDiff\osediff.py", line 10, in <module>
    from diffusers import DDPMScheduler
  File "C:\Users\admin\anaconda3\envs\osediff\lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "C:\Users\admin\anaconda3\envs\osediff\lib\site-packages\diffusers\utils\__init__.py", line 37, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "C:\Users\admin\anaconda3\envs\osediff\lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\Users\admin\anaconda3\envs\osediff\lib\site-packages\huggingface_hub\__init__.py)

**Comment by zelenooki87** [comment]
I am sorry. you are right. This was because I reinstalled OS, I thouth commit before working okay, but same case.
problem was because latest huggingface_hub installed by default in new environment
pip uninstall huggingface_hub
pip install huggingface-hub==0.24.6
solved issue.
closing Isue
