### ISSUE TITLE
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/notebook/data/group/LowLevelLLM/LLM/bert-base-uncased'. Use `repo_type` argument if needed.

### ISSUE THREAD

**Issue by zelenooki87** [cswry/OSEDiff#7]
Hi, 
Thank you for wonderfull work.
On windows system, this error is present during code execution:
python test_osediff.py -i input -o output --osediff_path preset/models/osediff.pkl --pretrained_model_name_or_path preset/models/stable-diffusion-2-1-base/ --ram_ft_path preset/models/DAPE.pth --ram_path preset/models/ram_swin_large_14m.pth
Traceback (most recent call last):
  File "C:\Users\Miki\OSEDiff\test_osediff.py", line 68, in <module>
    DAPE = ram(pretrained=args.ram_path,
  File "C:\Users\Miki\OSEDiff\ram\models\ram_lora.py", line 329, in ram
    model = RAMLora(**kwargs)
  File "C:\Users\Miki\OSEDiff\ram\models\ram_lora.py", line 109, in __init__
    self.tokenizer = init_tokenizer()
  File "C:\Users\Miki\OSEDiff\ram\models\utils.py", line 132, in init_tokenizer
    tokenizer = BertTokenizer.from_pretrained('/home/notebook/data/group/LowLevelLLM/LLM/bert-base-uncased', local_files_only=True)
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\transformers\tokenization_utils_base.py", line 1770, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/notebook/data/group/LowLevelLLM/LLM/bert-base-uncased'. Use `repo_type` argument if needed.

as a temporarily solution I use  utils.py from your previous repo:
https://github.com/cswry/SeeSR/blob/main/ram/models/utils.py

And everything works. :)

**Comment by AIisCool** [comment]
@zelenooki87 Are your results the same or better than SeeSR? Mine are much worse for some reason: https://github.com/cswry/OSEDiff/issues/9

**Comment by paomian001** [comment]
> Hi, Thank you for wonderfull work. On windows system, this error is present during code execution:
> 
> ```
> python test_osediff.py -i input -o output --osediff_path preset/models/osediff.pkl --pretrained_model_name_or_path preset/models/stable-diffusion-2-1-base/ --ram_ft_path preset/models/DAPE.pth --ram_path preset/models/ram_swin_large_14m.pth
> Traceback (most recent call last):
>   File "C:\Users\Miki\OSEDiff\test_osediff.py", line 68, in <module>
>     DAPE = ram(pretrained=args.ram_path,
>   File "C:\Users\Miki\OSEDiff\ram\models\ram_lora.py", line 329, in ram
>     model = RAMLora(**kwargs)
>   File "C:\Users\Miki\OSEDiff\ram\models\ram_lora.py", line 109, in __init__
>     self.tokenizer = init_tokenizer()
>   File "C:\Users\Miki\OSEDiff\ram\models\utils.py", line 132, in init_tokenizer
>     tokenizer = BertTokenizer.from_pretrained('/home/notebook/data/group/LowLevelLLM/LLM/bert-base-uncased', local_files_only=True)
>   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\transformers\tokenization_utils_base.py", line 1770, in from_pretrained
>     resolved_vocab_files[file_id] = cached_file(
>   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
>     resolved_file = hf_hub_download(
>   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
>     validate_repo_id(arg_value)
>   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
>     raise HFValidationError(
> huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/notebook/data/group/LowLevelLLM/LLM/bert-base-uncased'. Use `repo_type` argument if needed.
> ```
> 
> as a temporarily solution I use utils.py from your previous repo: https://github.com/cswry/SeeSR/blob/main/ram/models/utils.py
> 
> And everything works. :)

Hello, I also encountered the same error
May I ask where to download the pre trained model that tokenizer needs to load in untils.py?
Did you download it on this page

**Comment by paomian001** [comment]
> Hi, Thank you for wonderfull work. On windows system, this error is present during code execution:
> 
> ```
> python test_osediff.py -i input -o output --osediff_path preset/models/osediff.pkl --pretrained_model_name_or_path preset/models/stable-diffusion-2-1-base/ --ram_ft_path preset/models/DAPE.pth --ram_path preset/models/ram_swin_large_14m.pth
> Traceback (most recent call last):
>   File "C:\Users\Miki\OSEDiff\test_osediff.py", line 68, in <module>
>     DAPE = ram(pretrained=args.ram_path,
>   File "C:\Users\Miki\OSEDiff\ram\models\ram_lora.py", line 329, in ram
>     model = RAMLora(**kwargs)
>   File "C:\Users\Miki\OSEDiff\ram\models\ram_lora.py", line 109, in __init__
>     self.tokenizer = init_tokenizer()
>   File "C:\Users\Miki\OSEDiff\ram\models\utils.py", line 132, in init_tokenizer
>     tokenizer = BertTokenizer.from_pretrained('/home/notebook/data/group/LowLevelLLM/LLM/bert-base-uncased', local_files_only=True)
>   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\transformers\tokenization_utils_base.py", line 1770, in from_pretrained
>     resolved_vocab_files[file_id] = cached_file(
>   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
>     resolved_file = hf_hub_download(
>   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
>     validate_repo_id(arg_value)
>   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
>     raise HFValidationError(
> huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/notebook/data/group/LowLevelLLM/LLM/bert-base-uncased'. Use `repo_type` argument if needed.
> ```
> 
> as a temporarily solution I use utils.py from your previous repo: https://github.com/cswry/SeeSR/blob/main/ram/models/utils.py
> 
> And everything works. :)

Hello, I also encountered the same error
May I ask where to download the pre trained model that tokenizer needs to load in untils.py?
Did you download it on this page
![XX167F( `{)ACK%E`E$IX1O](https://github.com/cswry/OSEDiff/assets/153172845/da9cd435-06e1-4248-b123-65e6dfd72ae1)

**Comment by liuyifan6613** [comment]
> > Hi, Thank you for wonderfull work. On windows system, this error is present during code execution:
> > ```
> > python test_osediff.py -i input -o output --osediff_path preset/models/osediff.pkl --pretrained_model_name_or_path preset/models/stable-diffusion-2-1-base/ --ram_ft_path preset/models/DAPE.pth --ram_path preset/models/ram_swin_large_14m.pth
> > Traceback (most recent call last):
> >   File "C:\Users\Miki\OSEDiff\test_osediff.py", line 68, in <module>
> >     DAPE = ram(pretrained=args.ram_path,
> >   File "C:\Users\Miki\OSEDiff\ram\models\ram_lora.py", line 329, in ram
> >     model = RAMLora(**kwargs)
> >   File "C:\Users\Miki\OSEDiff\ram\models\ram_lora.py", line 109, in __init__
> >     self.tokenizer = init_tokenizer()
> >   File "C:\Users\Miki\OSEDiff\ram\models\utils.py", line 132, in init_tokenizer
> >     tokenizer = BertTokenizer.from_pretrained('/home/notebook/data/group/LowLevelLLM/LLM/bert-base-uncased', local_files_only=True)
> >   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\transformers\tokenization_utils_base.py", line 1770, in from_pretrained
> >     resolved_vocab_files[file_id] = cached_file(
> >   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
> >     resolved_file = hf_hub_download(
> >   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
> >     validate_repo_id(arg_value)
> >   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
> >     raise HFValidationError(
> > huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/notebook/data/group/LowLevelLLM/LLM/bert-base-uncased'. Use `repo_type` argument if needed.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > as a temporarily solution I use utils.py from your previous repo: https://github.com/cswry/SeeSR/blob/main/ram/models/utils.py
> > And everything works. :)
> 
> Hello, I also encountered the same error May I ask where to download the pre trained model that tokenizer needs to load in untils.py? Did you download it on this page ![XX167F( {)ACK%EE$IX1O](https://private-user-images.githubusercontent.com/153172845/344932674-da9cd435-06e1-4248-b123-65e6dfd72ae1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NzQ4NzksIm5iZiI6MTcxOTk3NDU3OSwicGF0aCI6Ii8xNTMxNzI4NDUvMzQ0OTMyNjc0LWRhOWNkNDM1LTA2ZTEtNDI0OC1iMTIzLTY1ZTZkZmQ3MmFlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwMjQyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWYxODdlNmM5ZDVmMmNiZmQ0OWM2YjYxZWUzOTEwOGZhNzcwYWZlM2IxNzFhMzBjYTdkNTEyNjZlMWI1NDk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QHbJxfBiEjiSRjUgIfXlIV9PeRJOdWh5WICAmjmeNZM)

注释\ram\models\utils.py 132行，使用131行的代码就可以了。

**Comment by paomian001** [comment]
> > > Hi, Thank you for wonderfull work. On windows system, this error is present during code execution:
> > > ```
> > > python test_osediff.py -i input -o output --osediff_path preset/models/osediff.pkl --pretrained_model_name_or_path preset/models/stable-diffusion-2-1-base/ --ram_ft_path preset/models/DAPE.pth --ram_path preset/models/ram_swin_large_14m.pth
> > > Traceback (most recent call last):
> > >   File "C:\Users\Miki\OSEDiff\test_osediff.py", line 68, in <module>
> > >     DAPE = ram(pretrained=args.ram_path,
> > >   File "C:\Users\Miki\OSEDiff\ram\models\ram_lora.py", line 329, in ram
> > >     model = RAMLora(**kwargs)
> > >   File "C:\Users\Miki\OSEDiff\ram\models\ram_lora.py", line 109, in __init__
> > >     self.tokenizer = init_tokenizer()
> > >   File "C:\Users\Miki\OSEDiff\ram\models\utils.py", line 132, in init_tokenizer
> > >     tokenizer = BertTokenizer.from_pretrained('/home/notebook/data/group/LowLevelLLM/LLM/bert-base-uncased', local_files_only=True)
> > >   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\transformers\tokenization_utils_base.py", line 1770, in from_pretrained
> > >     resolved_vocab_files[file_id] = cached_file(
> > >   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
> > >     resolved_file = hf_hub_download(
> > >   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
> > >     validate_repo_id(arg_value)
> > >   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
> > >     raise HFValidationError(
> > > huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/notebook/data/group/LowLevelLLM/LLM/bert-base-uncased'. Use `repo_type` argument if needed.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > as a temporarily solution I use utils.py from your previous repo: https://github.com/cswry/SeeSR/blob/main/ram/models/utils.py
> > > And everything works. :)
> > 
> > 
> > Hello, I also encountered the same error May I ask where to download the pre trained model that tokenizer needs to load in untils.py? Did you download it on this page ![XX167F( {)ACK%EE$IX1O](https://private-user-images.githubusercontent.com/153172845/344932674-da9cd435-06e1-4248-b123-65e6dfd72ae1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NzQ4NzksIm5iZiI6MTcxOTk3NDU3OSwicGF0aCI6Ii8xNTMxNzI4NDUvMzQ0OTMyNjc0LWRhOWNkNDM1LTA2ZTEtNDI0OC1iMTIzLTY1ZTZkZmQ3MmFlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwMjQyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWYxODdlNmM5ZDVmMmNiZmQ0OWM2YjYxZWUzOTEwOGZhNzcwYWZlM2IxNzFhMzBjYTdkNTEyNjZlMWI1NDk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QHbJxfBiEjiSRjUgIfXlIV9PeRJOdWh5WICAmjmeNZM)
> 
> 注释\ram\models\utils.py 132行，使用131行的代码就可以了。

谢谢 我下载了模型后就可以了

**Comment by 1343464520** [comment]
@liuyifan6613 @paomian001 @zelenooki87 请问下，你们在运行test_osediff.py时，self.unet.add_adapter(lora_conf_encoder, adapter_name="default_encoder")这行没报错么？我这行报错，发现add_adapter方法在UNet2DConditionModel类里就没有定义。请问你们怎么解决的？谢谢。

**Comment by DIAOROUQINGNIAN** [comment]
1、"注释\ram\models\utils.py 132行，使用131行的代码就可以了。"这个方法是可以的
2、然后输入的命令pretrained_model_name_or_path这里改成：--pretrained_model_name_or_path stabilityai/stable-diffusion-2-1-base \
3、如果出现huggingface连接问题之类的，可以在程序执行之前先输入：export HF_ENDPOINT="https://hf-mirror.com"     然后回车后，再执行我们需要运行的命令

**Comment by DIAOROUQINGNIAN** [comment]
> 1、"注释\ram\models\utils.py 132行，使用131行的代码就可以了。"这个方法是可以的 2、然后输入的命令pretrained_model_name_or_path这里改成：--pretrained_model_name_or_path stabilityai/stable-diffusion-2-1-base 3、如果出现huggingface连接问题之类的，可以在程序执行之前先输入：export HF_ENDPOINT="https://hf-mirror.com" 然后回车后，再执行我们需要运行的命令

注意：不需要下载[stable-diffusion-2-1-base]的任何文件

**Comment by syf0518** [comment]
感谢您的回复！不过我还想补充一点：
在出现huggingface连接问题时，Windows系统需要先输入：set HF_ENDPOINT=https://hf-mirror.com，回车后再运行test_osediff.py

> > 1、"注释\ram\models\utils.py 132行，使用131行的代码就可以了。"这个方法是可以的 2、然后输入的命令pretrained_model_name_or_path这里改成：--pretrained_model_name_or_path stabilityai/stable-diffusion-2-1-base 3、如果出现huggingface连接问题之类的，可以在程序执行之前先输入：export HF_ENDPOINT="https://hf-mirror.com" 然后回车后，再执行我们需要运行的命令
> 
> 注意：不需要下载[stable-diffusion-2-1-base]的任何文件

**Comment by leeqiaogithub** [comment]
> > > > 您好，感谢您的出色工作。在 Windows 系统上，代码执行过程中出现以下错误：
> > > > ```
> > > > python test_osediff.py -i input -o output --osediff_path preset/models/osediff.pkl --pretrained_model_name_or_path preset/models/stable-diffusion-2-1-base/ --ram_ft_path preset/models/DAPE.pth --ram_path preset/models/ram_swin_large_14m.pth
> > > > Traceback (most recent call last):
> > > >   File "C:\Users\Miki\OSEDiff\test_osediff.py", line 68, in <module>
> > > >     DAPE = ram(pretrained=args.ram_path,
> > > >   File "C:\Users\Miki\OSEDiff\ram\models\ram_lora.py", line 329, in ram
> > > >     model = RAMLora(**kwargs)
> > > >   File "C:\Users\Miki\OSEDiff\ram\models\ram_lora.py", line 109, in __init__
> > > >     self.tokenizer = init_tokenizer()
> > > >   File "C:\Users\Miki\OSEDiff\ram\models\utils.py", line 132, in init_tokenizer
> > > >     tokenizer = BertTokenizer.from_pretrained('/home/notebook/data/group/LowLevelLLM/LLM/bert-base-uncased', local_files_only=True)
> > > >   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\transformers\tokenization_utils_base.py", line 1770, in from_pretrained
> > > >     resolved_vocab_files[file_id] = cached_file(
> > > >   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
> > > >     resolved_file = hf_hub_download(
> > > >   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
> > > >     validate_repo_id(arg_value)
> > > >   File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
> > > >     raise HFValidationError(
> > > > huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/notebook/data/group/LowLevelLLM/LLM/bert-base-uncased'. Use `repo_type` argument if needed.
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > [作为](https://github.com/cswry/SeeSR/blob/main/ram/models/utils.py)临时解决方案，我使用您之前的 repo 中的 utils.py：https://github.com/cswry/SeeSR/blob/main/ram/models/utils.py
> > > > 并且一切正常。:)
> > > 
> > > 
> > > 你好，我也遇到了同样的错误，请问tokenizer需要在untils.py中加载的预训练模型在哪里下载？你是在这个页面下载的吗？![XX167F( {)ACK%EE$IX1O](https://private-user-images.githubusercontent.com/153172845/344932674-da9cd435-06e1-4248-b123-65e6dfd72ae1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NzQ4NzksIm5iZiI6MTcxOTk3NDU3OSwicGF0aCI6Ii8xNTMxNzI4NDUvMzQ0OTMyNjc0LWRhOWNkNDM1LTA2ZTEtNDI0OC1iMTIzLTY1ZTZkZmQ3MmFlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwMjQyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWYxODdlNmM5ZDVmMmNiZmQ0OWM2YjYxZWUzOTEwOGZhNzcwYWZlM2IxNzFhMzBjYTdkNTEyNjZlMWI1NDk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QHbJxfBiEjiSRjUgIfXlIV9PeRJOdWh5WICAmjmeNZM)
> > 
> > 
> > 注释\ram\models\utils.py 132行，使用131行的代码就可以了。
> 
> 谢谢 我下载了模型后就可以了

请问下载的是哪个模型？
