### ISSUE TITLE
fp16inference + tile option?

### ISSUE THREAD

**Issue by zelenooki87** [cswry/OSEDiff#8]
Is it possible to implement?
I can upscale images only up to 640x480pixels. (PC specs RTX 3090 24GB, 64GB RAM, Ryzen 7950X)
Thanks

**Comment by cswry** [comment]
Hello, we have added this function.

**Comment by zelenooki87** [comment]
Thank you very much. This is the best upscale method I have ever seen.

**Comment by zelenooki87** [comment]
I did not explicitly argumented fp16 inference because it is now turned on default.
now I am getting: python test_osediff.py -i input -o output --osediff_path preset/models/osediff.pkl --pretrained_model_name_or_path preset/models/stable-diffusion-2-1-base --ram_ft_path preset/models/DAPE.pth --ram_path preset/models/ram_swin_large_14m.pth
```
Traceback (most recent call last):
  File "C:\Users\Miki\OSEDiff\test_osediff.py", line 124, in <module>
    output_image = model(lq, prompt=validation_prompt)
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Miki\OSEDiff\my_utils\vaehook.py", line 440, in wrapper
    ret = fn(*args, **kwargs)
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Miki\OSEDiff\osediff.py", line 95, in forward
    lq_latent = self.vae.encode(lq.to(self.weight_dtype)).latent_dist.sample() * self.vae.config.scaling_factor
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\Miki\OSEDiff\models\autoencoder_kl.py", line 261, in encode
    moments = self.quant_conv(h)
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\peft\tuners\lora\layer.py", line 808, in forward
    result = self.base_layer(x, *args, **kwargs)
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same
```

**Comment by zelenooki87** [comment]
Redownloaded fp32 checkpoints. again same error:
`Traceback (most recent call last):
  File "C:\Users\Miki\OSEDiff\test_osediff.py", line 124, in <module>
    output_image = model(lq, prompt=validation_prompt)
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Miki\OSEDiff\my_utils\vaehook.py", line 440, in wrapper
    ret = fn(*args, **kwargs)
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Miki\OSEDiff\osediff.py", line 95, in forward
    lq_latent = self.vae.encode(lq.to(self.weight_dtype)).latent_dist.sample() * self.vae.config.scaling_factor
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\Miki\OSEDiff\models\autoencoder_kl.py", line 261, in encode
    moments = self.quant_conv(h)
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\peft\tuners\lora\layer.py", line 808, in forward
    result = self.base_layer(x, *args, **kwargs)
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\Miki\anaconda3\envs\osediff\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same`
solution for now is to run fp32 inference

**Comment by zelenooki87** [comment]
@cswry Could you please take a look?
I have the same problem in Ubuntu machine.

**Comment by cswry** [comment]
Hello, we update a new version.

Can you try fp16 mode again?

Thank you.

**Comment by zelenooki87** [comment]
Working fine now.
Thanks.
